version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
   postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smpp
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  smpp-processing:
    build: .
    depends_on:
      - kafka
      - elasticsearch
    environment:
      KAFKA_BROKER: "kafka:9092"
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"

  api:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "smpp"
